#-----------------------------------------------------------------------
# TITLE:
#    marsicons.tcl
#
# AUTHOR:
#    Will Duquette
#
# DESCRIPTION:
#    marsgui(n) package: standard icons
#
#    This module defines a set of standard icons for use in buttons,
#    etc.  All icons are defined in the ::marsgui::icon namespace; none
#    are exported.
#
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
# Icon definitions

namespace eval ::marsgui::icon:: {
    namespace import ::marsgui::mkicon
    
    proc mkiconPair {name pixels} {
        mkicon $name    $pixels [list . trans X black]
        mkicon ${name}d $pixels [list . trans X gray]
    }
    
    mkiconPair ::marsgui::icon::clear11 {
        ...XXXXX...
        ..XXXXXXX..
        .XX.XXX.XX.
        XX...X...XX
        XXX.....XXX
        XXXX...XXXX
        XXX.....XXX
        XX...X...XX
        .XX.XXX.XX.
        ..XXXXXXX..
        ...XXXXX...
        ...........
    }
    
    mkicon ::marsgui::icon::filter16 {
        ........XXXXX...
        .......X.X.X.X..
        ......X.X.X.X.X.
        .....X.X.X.X.X.X
        .....XX.X.X.X.XX
        .....X.X.X.X.X.X
        .....XX.X.X.X.XX
        .....X.X.X.X.X.X
        ......X.X.X.X.X.
        .....XXX.X.X.X..
        ....XXX.XXXXX...
        ...XXX..........
        ..XXX....XXXXXXX
        .XXX......XXXXX.
        XXX........XXX..
        XX..........X...
    } {
        . trans
        X black
    }

    mkicon ::marsgui::icon::search16 {
        ........XXXXX...
        .......X.....X..
        ......X..XXX..X.
        .....X..X...X..X
        .....X.........X
        .....X.........X
        .....X.........X
        .....X.........X
        ......X.......X.
        .....XXX.....X..
        ....XXX.XXXXX...
        ...XXX..........
        ..XXX....XXXXXXX
        .XXX......XXXXX.
        XXX........XXX..
        XX..........X...
    } {
        . trans
        X black
    }

    mkicon ::marsgui::icon::pencil22 {
        ......................
        ......................
        ...............XXX....
        ..............XeeeX...
        .............XeeeeeX..
        ............X,XeeeeX..
        ...........X,,,XeeeX..
        ..........X,,,X,XeX...
        .........X,,,X,,,X....
        ........X,,,X,,,X.....
        .......X,,,X,,,X......
        ......X,,,X,,,X.......
        .....X,,,X,,,X........
        ....XwX,X,,,X.........
        ....XwwX,,,X..........
        ...XwwwwX,X...........
        ...XwwwwwX............
        ...XXwwXX.............
        ..XXXXX...............
        ..XX..................
        ......................
        ......................
    } {
        .  trans
        X  #000000
        e  #E77F7F
        ,  #EFB311
        w  #BDA565
    }


    mkicon ::marsgui::icon::plus22 {
        ......................
        ......................
        ......................
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        ...XXXXXXXXXXXXXXXX...
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        .........XXXX.........
        ......................
        ......................
        ......................
    } {
        .  trans
        X  #000000
    }


    mkicon ::marsgui::icon::help22 {
        ......................
        ......................
        ........XXXXXX........
        ......XXXXXXXXXX......
        .....XXXXXXXXXXXX.....
        ....XXXXX....XXXXX....
        ....XXXX......XXXX....
        .....XX.......XXXX....
        .............XXXX.....
        ............XXXX......
        ...........XXXX.......
        ..........XXXX........
        .........XXXX.........
        .........XXXX.........
        ..........XX..........
        ......................
        ..........XX..........
        .........XXXX.........
        .........XXXX.........
        ..........XX..........
        ......................
        ......................
    } {
        .  trans
        X  #000000
    }

    mkicon ::marsgui::icon::x22 {
        ......................
        ......................
        ......................
        ...XXX..........XXX...
        ...XXXX........XXXX...
        ...XXXXX......XXXXX...
        ....XXXXX....XXXXX....
        .....XXXXX..XXXXX.....
        ......XXXXXXXXXX......
        .......XXXXXXXX.......
        ........XXXXXX........
        ........XXXXXX........
        .......XXXXXXXX.......
        ......XXXXXXXXXX......
        .....XXXXX..XXXXX.....
        ....XXXXX....XXXXX....
        ...XXXXX......XXXXX...
        ...XXXX........XXXX...
        ...XXX..........XXX...
        ......................
        ......................
        ......................
    } {
        .  trans
        X  #FF0000
    }

    mkicon ::marsgui::icon::check22 {
        ......................
        ......................
        ......................
        ......................
        .................XX...
        ...X...........XXX....
        ...XX........XXXX.....
        ....XX.....XXXXX......
        ....XXX..XXXXXX.......
        ....XXXXXXXXXX........
        ....XXXXXXXXX.........
        .....XXXXXXX..........
        .....XXXXXX...........
        .....XXXXX............
        .....XXXX.............
        ......XX..............
        ......X...............
        ......................
        ......................
        ......................
        ......................
        ......................
    } {
        .  trans
        X  #009900
    }

    mkicon ::marsgui::icon::play22 {
        ......................
        ......................
        ......................
        ....XX................
        ....XXXX..............
        ....XXXXXX............
        ....XXXXXXXX..........
        ....XXXXXXXXXX........
        ....XXXXXXXXXXXX......
        ....XXXXXXXXXXXXXX....
        ....XXXXXXXXXXXX......
        ....XXXXXXXXXX........
        ....XXXXXXXX..........
        ....XXXXXX............
        ....XXXX..............
        ....XX................
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
    } {
        .  trans
        X  #000000
    }


    mkicon ::marsgui::icon::pause22 {
        ......................
        ......................
        ......................
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        .....XXXX....XXXX.....
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
    } {
        .  trans
        X  #000000
    }


    mkicon ::marsgui::icon::rewind22 {
        ......................
        ......................
        ......................
        ...X............XX....
        ...X..........XXXX....
        ...X........XXXXXX....
        ...X......XXXXXXXX....
        ...X....XXXXXXXXXX....
        ...X..XXXXXXXXXXXX....
        ...XXXXXXXXXXXXXXX....
        ...X..XXXXXXXXXXXX....
        ...X....XXXXXXXXXX....
        ...X......XXXXXXXX....
        ...X........XXXXXX....
        ...X..........XXXX....
        ...X............XX....
        ......................
        ......................
        ......................
        ......................
        ......................
        ......................
    } {
        .  trans
        X  #000000
    }


    mkicon ::marsgui::icon::first16 {
        ................
        .X.....X.....X..
        .X....XX....XX..
        .X...XXX...XXX..
        .X..XXXX..XXXX..
        .X.XXXXX.XXXXX..
        .XXXXXXXXXXXXX..
        .X.XXXXX.XXXXX..
        .X..XXXX..XXXX..
        .X...XXX...XXX..
        .X....XX....XX..
        .X.....X.....X..
        ................
        ................
        ................
        ................
    } {
        .  trans
        X  #000000
    }


    mkicon ::marsgui::icon::prev16 {
        ................
        .......X.....X..
        ......XX....XX..
        .....XXX...XXX..
        ....XXXX..XXXX..
        ...XXXXX.XXXXX..
        ..XXXXXXXXXXXX..
        ...XXXXX.XXXXX..
        ....XXXX..XXXX..
        .....XXX...XXX..
        ......XX....XX..
        .......X.....X..
        ................
        ................
        ................
        ................
    } {
        .  trans
        X  #000000
    }


    mkicon ::marsgui::icon::next16 {
        ................
        .X.....X........
        .XX....XX.......
        .XXX...XXX......
        .XXXX..XXXX.....
        .XXXXX.XXXXX....
        .XXXXXXXXXXXX...
        .XXXXX.XXXXX....
        .XXXX..XXXX.....
        .XXX...XXX......
        .XX....XX.......
        .X.....X........
        ................
        ................
        ................
        ................
    } {
        .  trans
        X  #000000
    }


    mkicon ::marsgui::icon::last16 {
        ................
        .X.....X.....X..
        .XX....XX....X..
        .XXX...XXX...X..
        .XXXX..XXXX..X..
        .XXXXX.XXXXX.X..
        .XXXXXXXXXXXXX..
        .XXXXX.XXXXX.X..
        .XXXX..XXXX..X..
        .XXX...XXX...X..
        .XX....XX....X..
        .X.....X.....X..
        ................
        ................
        ................
        ................
    } {
        .  trans
        X  #000000
    }

}


